services:
  go-backend:
    container_name: go-backend
    build: ./go-backend
    restart: unless-stopped
    env_file:
      - ./common.env
    ports:
      - 8080:8080
    depends_on: 
      - db
  
  python-bot:
    container_name: python-bot
    build: ./python-bot
    restart: unless-stopped
    env_file:
      - ./common.env
    depends_on:
      - go-backend

  db:
    container_name: db
    image: postgres:17
    env_file:
      - ./common.env
    ports:
      - 5432:5432